type ArticleCommentsTranslator = (key: string, values?: Record<string, string>) => string;

/**
 * 댓글 섹션에서 쓰는 번역 문자열을 한 번에 구성합니다.
 */
export const createArticleCommentsText = (t: ArticleCommentsTranslator) => ({
  actionDeleteLabel: t('delete'),
  actionEditLabel: t('edit'),
  actionMenuLabel: t('actionMenuLabel'),
  actionMenuPanelLabel: t('actionMenuPanelLabel'),
  actionReplyLabel: t('reply'),
  closeLabel: t('close'),
  composeAuthorBlogUrlInvalidMessage: t('composeAuthorBlogUrlInvalid'),
  composeAuthorBlogUrlLabel: t('composeAuthorBlogUrlLabel'),
  composeAuthorBlogUrlPlaceholder: t('composeAuthorBlogUrlPlaceholder'),
  composeAuthorNameLabel: t('composeAuthorNameLabel'),
  composeAuthorNamePlaceholder: t('composeAuthorNamePlaceholder'),
  composeCharacterCountLabel: t('composeCharacterCountLabel'),
  composeContentShortcutHint: t('composeContentShortcutHint'),
  composePasswordLabel: t('composePasswordLabel'),
  composePasswordPlaceholder: t('composePasswordPlaceholder'),
  composePlaceholder: t('composePlaceholder'),
  composeReplyContentLabel: t('composeReplyContentLabel'),
  composeReplyPreviewLabel: t('composeReplyPreviewLabel'),
  delete: t('delete'),
  deleteConfirm: t('deleteConfirm'),
  deleteModalHint: t('deleteModalHint'),
  deleteModalTitle: t('deleteModalTitle'),
  deletedPlaceholder: t('deletedPlaceholder'),
  description: t('description'),
  edit: t('edit'),
  editConfirm: t('editConfirm'),
  editContentUnchanged: t('editContentUnchanged'),
  editModalTitle: t('editModalTitle'),
  emptyItems: t('emptyItems'),
  loading: t('loading'),
  modalCloseAriaLabel: t('modalCloseAriaLabel'),
  paginationLabel: t('paginationLabel'),
  password: t('password'),
  reply: t('reply'),
  report: t('report'),
  requiredField: t('requiredField'),
  retry: t('retry'),
  secretVerifyFailed: t('secretVerifyFailed'),
  sortLabel: t('sortLabel'),
  sortLatest: t('sortLatest'),
  sortOldest: t('sortOldest'),
  submit: t('submit'),
  title: t('title'),
  toastCreateError: t('toastCreateError'),
  toastCreateSuccess: t('toastCreateSuccess'),
  toastDeleteError: t('toastDeleteError'),
  toastDeleteSuccess: t('toastDeleteSuccess'),
  toastEditError: t('toastEditError'),
  toastEditSuccess: t('toastEditSuccess'),
  toastReplyError: t('toastReplyError'),
  toastReplySuccess: t('toastReplySuccess'),
});

export type ArticleCommentsText = ReturnType<typeof createArticleCommentsText>;
